- hosts: all
  vars:
    ansible_python_interpreter: auto_legacy_silent
  become: true
  tasks:
   - name: update 
     apt:
       update_cache: yes
       
   - name: install docker
     apt:
       name: docker.io
       state: present
     
   - name: Log into DockerHub
     docker_login:
      username: harris2711
      password: Harry@2711
      email: mohammedharris556@gmail.com
      
   - name: Pull image from docker hub
     command: docker pull harris2711/harrisjenkins:"{{buildNumber}}"

   - name: Stop current running container
     command: docker stop harry-c1
     ignore_errors: yes

   - name: Remove stopped container
     command: docker rm harry-c1
     ignore_errors: yes

   - name: Run a container from the pulled image
     command: docker run -d --name harry-c1 -p 80:8080 harris2711/harrisjenkins:"{{buildNumber}}"
